import type { PersonalOSState } from "./types";

const id = (prefix: string, index: number) => `${prefix}-${index.toString().padStart(3, "0")}`;

function isoDate(offset = 0) {
  const date = new Date();
  date.setHours(12, 0, 0, 0);
  date.setDate(date.getDate() + offset);
  return date.toISOString().slice(0, 10);
}

export function createSeedState(): PersonalOSState {
  return {
    version: 1,
    projects: [
      {
        id: "project-orbit",
        title: "INTERACTIVE ORBIT EXPLORER",
        category: "UZAY / YARATICI",
        description: "Yörünge fiziğini sezgisel ve görsel bir deneyime dönüştüren etkileşimli web projesi.",
        status: "progress",
        priority: "high",
        startDate: isoDate(-18),
        dueDate: isoDate(34),
        progress: 68,
        tags: ["uzay", "simülasyon", "ui"],
        nextAction: "Yörünge hızı görselleştirmesini uygula",
        notes: "Fiziksel doğruluk ile sezgisel anlatım arasındaki dengeyi koru.",
        links: ["Araştırma notları", "Figma taslağı"],
        subtasks: [
          { id: "orbit-s1", title: "Yörünge denklemlerini araştır", completed: true },
          { id: "orbit-s2", title: "Arayüz iskeletini tasarla", completed: true },
          { id: "orbit-s3", title: "Hız görselleştirmesini uygula", completed: false },
          { id: "orbit-s4", title: "Kontrolleri test et", completed: false },
          { id: "orbit-s5", title: "Mikro animasyonları cilala", completed: false },
        ],
      },
      {
        id: "project-personal-os",
        title: "PERSONAL OS",
        category: "ÜRÜN / SİSTEM",
        description: "Hayatı, işleri ve merakı tek bir sakin çalışma sisteminde birleştiren kişisel uygulama.",
        status: "review",
        priority: "high",
        startDate: isoDate(-25),
        dueDate: isoDate(10),
        progress: 82,
        tags: ["ürün", "sistem"],
        nextAction: "Mobil takvim akışını gözden geçir",
        subtasks: [
          { id: "pos-s1", title: "Bilgi mimarisini tamamla", completed: true },
          { id: "pos-s2", title: "Komuta merkezini kur", completed: true },
          { id: "pos-s3", title: "Mobil akışı test et", completed: false },
        ],
      },
      {
        id: "project-future-ui",
        title: "FUTURE UI EXPERIMENTS",
        category: "TASARIM / LAB",
        description: "Alternatif gelecek arayüzleri için küçük, hızlı ve yayınlanabilir görsel deneyler.",
        status: "todo",
        priority: "medium",
        startDate: isoDate(2),
        dueDate: isoDate(25),
        progress: 24,
        tags: ["retro-fütürizm", "arayüz"],
        nextAction: "Ay kolonisi kontrol paneli için 3 eskiz üret",
        subtasks: [
          { id: "fui-s1", title: "Referans panosu hazırla", completed: true },
          { id: "fui-s2", title: "Üç konsept eskizi çiz", completed: false },
          { id: "fui-s3", title: "Bir konsepti prototiple", completed: false },
        ],
      },
      {
        id: "project-photo",
        title: "KIYI FOTOĞRAF SERİSİ",
        category: "FOTOĞRAF / KİŞİSEL",
        description: "İstanbul kıyılarını sakin, arşivsel bir görsel dille belgeleyen mini seri.",
        status: "backlog",
        priority: "low",
        startDate: isoDate(12),
        progress: 0,
        tags: ["fotoğraf", "şehir"],
        nextAction: "İlk yürüyüş rotasını seç",
        subtasks: [
          { id: "photo-s1", title: "Rota seç", completed: false },
          { id: "photo-s2", title: "12 kare çek", completed: false },
        ],
      },
    ],
    tasks: [
      {
        id: "task-orbit-visual",
        title: "Yörünge hızı görselleştirmesini uygula",
        category: "todo",
        completed: false,
        priority: "high",
        date: isoDate(0),
        time: "10:30",
        projectId: "project-orbit",
        notes: "Önce dairesel yörünge, sonra eliptik varyasyon.",
        subtasks: [
          { id: "task-orbit-v1", title: "Hız vektörünü çiz", completed: true },
          { id: "task-orbit-v2", title: "Kontrol değerlerini bağla", completed: false },
        ],
      },
      {
        id: "task-english",
        title: "Titan atmosferini İngilizce anlat — 15 dakika",
        category: "todo",
        completed: false,
        priority: "medium",
        date: isoDate(0),
        time: "18:30",
        recurrence: "Haftada 3",
        subtasks: [],
      },
      {
        id: "task-workout",
        title: "45 dakikalık tam vücut antrenmanı",
        category: "todo",
        completed: false,
        priority: "medium",
        date: isoDate(0),
        time: "20:00",
        recurrence: "Haftada 3",
        subtasks: [],
      },
      {
        id: "task-site-review",
        title: "Kıbleteyn mobil sayfalarını kontrol et",
        category: "todo",
        completed: false,
        priority: "high",
        date: isoDate(1),
        time: "09:30",
        subtasks: [],
      },
      {
        id: "task-subscription",
        title: "Alan adı yenilemesini kontrol et",
        category: "todo",
        completed: true,
        priority: "medium",
        date: isoDate(-1),
        subtasks: [],
      },
      {
        id: "buy-book",
        title: "The Design of Everyday Things",
        category: "purchase",
        completed: false,
        priority: "medium",
        estimate: "₺520",
        link: "Kitap listesi",
        notes: "İkinci el seçeneklerine bak.",
        subtasks: [],
      },
      {
        id: "buy-tripod",
        title: "Kompakt masa tripodu",
        category: "purchase",
        completed: false,
        priority: "low",
        estimate: "₺850",
        notes: "Telefon ve kamera ile uyumlu olmalı.",
        subtasks: [],
      },
      {
        id: "place-museum",
        title: "İstanbul Arkeoloji Müzeleri",
        category: "place",
        completed: false,
        priority: "medium",
        city: "İstanbul",
        placeType: "Müze",
        date: isoDate(7),
        notes: "Doğa tarihi ve antik teknoloji bölümlerine odaklan.",
        subtasks: [],
      },
      {
        id: "place-balat",
        title: "Balat fotoğraf yürüyüşü",
        category: "place",
        completed: false,
        priority: "low",
        city: "İstanbul",
        placeType: "Fotoğraf rotası",
        notes: "Sabah ışığında bir saatlik rota.",
        subtasks: [],
      },
    ],
    calendarItems: [
      { id: "cal-1", title: "Antrenman", date: isoDate(0), time: "20:00", type: "personal" },
      { id: "cal-2", title: "Orbit Explorer", date: isoDate(0), time: "10:30", type: "project" },
      { id: "cal-3", title: "İngilizce konuşma", date: isoDate(0), time: "18:30", type: "personal" },
      { id: "cal-4", title: "Kıbleteyn site kontrolü", date: isoDate(1), time: "09:30", type: "work" },
      { id: "cal-5", title: "Müze keşfi", date: isoDate(7), time: "11:00", type: "event" },
      { id: "cal-6", title: "Haftalık reset", date: isoDate(2), time: "19:00", type: "personal" },
      { id: "cal-7", title: "Tasarım laboratuvarı", date: isoDate(4), time: "21:00", type: "project" },
      { id: "cal-8", title: "Ekip toplantısı", date: isoDate(-2), time: "14:00", type: "work" },
      { id: "cal-9", title: "Diksiyon kaydı", date: isoDate(3), time: "18:00", type: "personal" },
    ],
    notes: [
      {
        id: "note-hohmann",
        title: "Hohmann Transferi",
        folder: "UZAY / Yörünge Mekaniği",
        content: "# Hohmann transferi\n\nİki dairesel yörünge arasında geçiş için kullanılan yakıt-verimli eliptik manevra.\n\n- İlk yanma: apoapsisi yükseltir\n- İkinci yanma: yeni yörüngeyi daireselleştirir\n\n[ ] Orbit Explorer içinde basit diyagram hazırla",
        tags: ["uzay", "fizik"],
        favorite: true,
        archived: false,
        updatedAt: isoDate(0),
      },
      {
        id: "note-retro",
        title: "Retro-fütürizm neden hâlâ gelecek gibi?",
        folder: "TASARIM / Retro Fütürizm",
        content: "Geçmişin gelecek tasvirleri, bugünün arayüzlerinden daha fiziksel ve iyimser. Malzeme, mekanik kontrol ve sınırları görünür kılmak tasarımı daha inandırıcı yapıyor.",
        tags: ["tasarım", "araştırma"],
        favorite: true,
        archived: false,
        updatedAt: isoDate(-2),
      },
      {
        id: "note-cretaceous",
        title: "Kretase ses manzarası",
        folder: "DİNOZORLAR / Kretase",
        content: "Araştırma sorusu: Kuşlara ve timsahlara bakarak dinozor sesleri hakkında ne çıkarabiliriz? Görsel bir ses haritası fikri.",
        tags: ["dinozorlar", "ses"],
        favorite: false,
        archived: false,
        updatedAt: isoDate(-5),
      },
      {
        id: "note-app-ideas",
        title: "Küçük deney fikirleri",
        folder: "FİKİRLER / Uygulamalar",
        content: "- Titan atmosfer kartı\n- CRT piksel laboratuvarı\n- Ay üssü vardiya paneli\n- Fosil yaşlandırma aracı",
        tags: ["fikir", "deney"],
        favorite: false,
        archived: false,
        updatedAt: isoDate(-8),
      },
    ],
    workNotes: [
      {
        id: "work-umre",
        title: "Umre landing page",
        workspace: "WEB SİTESİ",
        description: "Mobil hero ve form akışındaki son düzenlemeler.",
        status: "Devam Ediyor",
        priority: "high",
        date: isoDate(0),
        checklist: [
          { id: "work-umre-1", title: "Hero metnini güncelle", completed: true },
          { id: "work-umre-2", title: "Görselleri sıkıştır", completed: true },
          { id: "work-umre-3", title: "Mobil boşlukları düzelt", completed: false },
          { id: "work-umre-4", title: "Formu uçtan uca kontrol et", completed: false },
        ],
      },
      {
        id: "work-turasistan",
        title: "Tur paketi kartları",
        workspace: "TURASİSTAN",
        description: "Yoğun sezon öncesi kart hiyerarşisi ve fiyat alanları.",
        status: "Bekliyor",
        priority: "medium",
        date: isoDate(2),
        checklist: [
          { id: "work-tour-1", title: "Mevcut kartları denetle", completed: false },
          { id: "work-tour-2", title: "Yeni varyantı hazırla", completed: false },
        ],
      },
      {
        id: "work-guideline",
        title: "Sosyal medya görsel sistemi",
        workspace: "TASARIM",
        description: "Kampanya görselleri için ölçü, tipografi ve renk standardı.",
        status: "Tamamlandı",
        priority: "medium",
        date: isoDate(-6),
        checklist: [
          { id: "work-guide-1", title: "Boyut setini çıkar", completed: true },
          { id: "work-guide-2", title: "Örnekleri onaylat", completed: true },
        ],
      },
    ],
    curiosityQuestions: [
      { id: "q-space-1", category: "UZAY", question: "Uydular neden doğrudan Dünya'ya düşmüyor?" },
      { id: "q-space-2", category: "UZAY", question: "Titan'ın yüzeyinde durmak gerçekte nasıl hissettirirdi?" },
      { id: "q-space-3", category: "UZAY", question: "Venüs neden Merkür'den daha sıcak?" },
      { id: "q-space-4", category: "UZAY", question: "Bir uzay aracı, uçak gibi dönmeden yörüngesini nasıl değiştirir?" },
      { id: "q-dino-1", category: "DİNOZORLAR", question: "Bir Tyrannosaurus gerçekte nasıl bir ses çıkarırdı?" },
      { id: "q-dino-2", category: "DİNOZORLAR", question: "Bazı dinozorlar neden tüy geliştirdi?" },
      { id: "q-dino-3", category: "DİNOZORLAR", question: "Kretase döneminde Dünya nasıl kokuyor ve nasıl duyuluyor olabilirdi?" },
      { id: "q-tech-1", category: "TEKNOLOJİ", question: "CRT ekranlar neden modern ekranlardan görsel olarak farklı hissediyordu?" },
      { id: "q-tech-2", category: "TEKNOLOJİ", question: "Bilgisayarlar GPU'lardan önce grafikleri nasıl oluşturuyordu?" },
      { id: "q-tech-3", category: "TEKNOLOJİ", question: "Dokunmatik ekran hiç bulunmasaydı akıllı telefonlar nasıl görünürdü?" },
      { id: "q-design-1", category: "TASARIM", question: "Retro-fütürizm eski olduğu hâlde neden hâlâ fütüristik hissettiriyor?" },
      { id: "q-design-2", category: "TASARIM", question: "Yoğun bilgi içeren bir arayüzü okunabilir yapan nedir?" },
      { id: "q-design-3", category: "TASARIM", question: "NASA bir tüketici telefonu arayüzünü nasıl tasarlardı?" },
      { id: "q-physics-1", category: "FİZİK", question: "Kara deliğe yaklaşırken zaman neden farklı akar?" },
      { id: "q-future-1", category: "GELECEK", question: "Mars'ta kalıcı bir şehir yer altında kurulabilir mi?" },
      { id: "q-weird-1", category: "TUHAF BİLİM", question: "Modern atmosferde bir dinozor biyolojik olarak hayatta kalabilir miydi?" },
    ],
    weeklyTargets: [
      { id: "weekly-sport", label: "Spor", shortLabel: "SPOR", current: 1, target: 3, unit: "seans", tone: "green" },
      { id: "weekly-english", label: "İngilizce", shortLabel: "ENGLISH", current: 2, target: 3, unit: "konuşma", tone: "cyan" },
      { id: "weekly-diction", label: "Diksiyon", shortLabel: "DİKSİYON", current: 1, target: 3, unit: "kayıt", tone: "amber" },
      { id: "weekly-curiosity", label: "Merak", shortLabel: "MERAK", current: 0, target: 1, unit: "misyon", tone: "amber" },
      { id: "weekly-creative", label: "Yaratıcı", shortLabel: "YARATICI", current: 1.5, target: 3, unit: "saat", tone: "green" },
      { id: "weekly-social", label: "Sosyal", shortLabel: "SOSYAL", current: 1, target: 2, unit: "ortam", tone: "cyan" },
      { id: "weekly-solo", label: "Solo keşif", shortLabel: "SOLO", current: 0, target: 1, unit: "çıkış", tone: "neutral" },
      { id: "weekly-career", label: "Kariyer", shortLabel: "KARİYER", current: 1, target: 3, unit: "saat", tone: "green" },
    ],
    weeklyHistory: [
      { id: "week-previous", label: "Geçen hafta", score: 71, summary: "Ritim kuruldu; yaratıcı süre hedefi sakin şekilde devam ediyor." },
      { id: "week-two-ago", label: "2 hafta önce", score: 64, summary: "Spor düzeni başladı ve ilk solo keşif tamamlandı." },
    ],
    creativeIdeas: [
      { id: id("creative", 1), title: "UZAY ARACI KOKPİTİ", description: "Sadece kritik uçuş kararlarına odaklanan analog-dijital kontrol paneli.", saved: true },
      { id: id("creative", 2), title: "DİNOZOR MÜZESİ EKRANI", description: "Bir fosilin yaşam öyküsünü katman katman açan interaktif kiosk.", saved: false },
      { id: id("creative", 3), title: "TITAN ATMOSFER KARTI", description: "Basınç, rüzgâr ve gökyüzü rengini tek bir bilimsel bilgi kartında görselleştir.", saved: false },
      { id: id("creative", 4), title: "1984'TE TELEFON", description: "Modern telefonu mekanik düğmeler ve CRT mantığıyla yeniden tasarla.", saved: false },
      { id: id("creative", 5), title: "AY KOLONİSİ ARAYÜZÜ", description: "Enerji, oksijen ve vardiya durumunu gösteren sakin operasyon ekranı.", saved: false },
    ],
    spaceExperiments: [
      { id: "space-orbit", topic: "Yörünge Mekaniği", learn: "Yörüngenin neden sürekli düşmek olduğunu anla.", experiment: "Basit bir yörünge simülasyonu kur veya var olanı değiştir.", status: "active" },
      { id: "space-propulsion", topic: "İtki Sistemleri", learn: "İtki, özgül itki ve kütle oranı arasındaki ilişkiyi keşfet.", experiment: "Üç motor tipini tek sayfalık karşılaştırmada göster.", status: "ready" },
      { id: "space-control", topic: "Kontrol Sistemleri", learn: "Bir uzay aracının yönelimini nasıl koruduğunu öğren.", experiment: "Tepki tekeri için basit etkileşimli kontrol taslağı yap.", status: "ready" },
      { id: "space-thermal", topic: "Termal Sistemler", learn: "Uzayda ısının neden ayrı bir tasarım problemi olduğunu anla.", experiment: "Bir uydu için ısı akış diyagramı hazırla.", status: "locked" },
    ],
    activityLogs: [
      { id: "log-1", area: "body", title: "Tam vücut antrenmanı", date: isoDate(-3), duration: 48 },
      { id: "log-2", area: "english", title: "Mars habitatını İngilizce anlattım", date: isoDate(-2), duration: 16 },
      { id: "log-3", area: "creative", title: "Orbit Explorer arayüzü", date: isoDate(-1), duration: 90 },
    ],
    recentQuestionIds: ["q-space-1", "q-tech-1", "q-design-2"],
  };
}

